* Products
** Electronics
*** Lenovo ThinkPad E15
I've been using this laptop since the fall of 2020 and I overall like the machine.
*** JLab wireless headphones
** Clothing
*** Arc'teryx Jacket
** Sports
*** Standard lacrosse ball
This was a very high quality purchase I must of made back in 2015. I can't believe I even have it kicking around after all these years. It was all of $5 and it gives my feet a nice massage at the end of long days. It can also be used for it's original purpose if you know how to play lacrosse. The next time you're at any sort of sports store and you see one of these for sale, please buy one.
*** Hoka Torrent 2
** Software
*** Emacs
One of the best pieces of software ever created. The fact that it's 100% free is a gift to the world that has stood strong for the last 50 years, and could probably go another 50 years. In fact, this website was created using Emacs. I highly recommend checking out the documentation and maybe watching a few videos about the subject to see if it's right for you.
* Services
