I have been lucky to travel to a variety of places in Canada. It's something that many Canadians don't get a chance to do because the price of travel in this vast country is nothing short of scandelous. Add on the high price of accommadations and food, and I can see why many people would prefer to spend their vacation dollars elsewhere.

Through various work and school opportunities, I've visted each one of Canada's main geographic regions. I'd like to share my thoughts about each place, and hopefully encourage those who can to visit them. I think this can be said about traval in general: the most valuable thing about the places I've been to is the people who call those places home.

* The West Coast
I've been to every place you've heard of, and many you'll never visit. Not literally, but it's much more than most people will ever visit.
* The Prairie Provinces
I've only spent a few brief months living here so I can't say I know the area as well as other regions.
* Central Canada
This is where I currently live.
* The Atlantic Region
I was lucky to work for a company that was stationed in the central part of Newfoundland aptly name Central for about 6 months.
* The North
This experience was like something out a movie. There is something special about places as vast as the northern reaches of Canada. 
